version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  my_secret:
    secure: arCq90fXn5X2pPHSgvMKpiVPlxqrzESJBOI5JxmShHo=
install:
- cmd: appveyor-tools\secure-file -decrypt MailgunAddressValidatorTests\app.config.enc -secret %my_secret%
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: lPLoSbylMv4JqmPOwZBnBuZahKFJGrqXxPSxsWLrWAdXSRHjTNJCy5GF6B+k9aOG
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: nkjDKrNWkieMXDYfxDISvLAX6YHd7nT6ASO8+AVVdoMgK7Q7bX3JVUjZPbsR0gBI
  on:
    branch: master